### ISSUE TITLE
Error running "Step_09_02_VACCINES_L3_counts_new.R"

### ISSUE THREAD

**Issue by elisacm98** [UMC-Utrecht-RWE/ConcePTION-Level3#5]
Hi, 

We have been running the VACCINES part of the L3 and we had the following error in the loop for in line 550:

Error in vaccines_files_females[[vx_files]] : 
  sub?ndice fuera de  los l?mites

The condition is for (i in 1: length(vaccines_files_females)) and in our case vaccines_files_females is empty, so its length is 0.  As I have been running the code I noticied that the couts are made by the ATC code, but we haven't got that variable in our dataset. We use the variable vx_type and not the vx_atc to differentiate the vaccines. Could be this the reason of our errror? How can it be solved?

**Comment by t-andresvaz** [comment]
Fixed by solution described on issue #7

**Comment by elisacm98** [comment]
Hi @relbersumcu, @t-andresvaz 

Solution to issue #7 does not fix our problems. In our case we have problems executing VACCINES scripts and I think it is because the variable vx_atc is empty, as we do not have that information. We differenciate the vaccines using the variable vx_type. However, we have noticed that in the script only the vx_atc is used for calculations.

**Comment by t-andresvaz** [comment]
Ok. Its reopened. We will double check and reply soon.

**Comment by t-andresvaz** [comment]
@relbersumcu can you take a look to this issue?

**Comment by frasansa** [comment]
Same issue for VID datasource:

> [1] "Creating Table 13:  Number of administrations/record by ATC 7 level in the study population by year of administration/record and by meaning."
> [1] "Creating counts for females "
> **Error in vaccines_files_females[[vx_files]] : subscript out of bounds**
> Timing stopped at: 40.64 7.75 36.23
